"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { useCart } from "@/lib/cart";
import { supabase } from "@/lib/supabase";
import { ClipboardCheck, CreditCard, Truck } from "lucide-react";

const shippingOptions=[{id:'retiro',name:'Retiro/coordinar',cost:0},{id:'cordoba',name:'Córdoba capital',cost:2500},{id:'interior',name:'Interior del país',cost:5500}];

export default function CheckoutPage(){
  const {items,subtotal,clearCart}=useCart();
  const [form,setForm]=useState({name:'',email:'',phone:'',address:'',city:'',postalCode:'',notes:''});
  const [ship,setShip]=useState('cordoba'); const [loading,setLoading]=useState(false);
  const shipping=shippingOptions.find(x=>x.id===ship)!; const total=useMemo(()=>subtotal+shipping.cost,[subtotal,shipping]);
  async function createOrder(){ if(!items.length) return alert('El carrito está vacío'); if(!form.name||!form.email||!form.phone) return alert('Completá nombre, email y teléfono'); setLoading(true); const {data,error}=await supabase.from('orders').insert({customer_email:form.email,customer_name:form.name,customer_phone:form.phone,shipping_method:ship,shipping_address:form.address,shipping_city:form.city,shipping_postal_code:form.postalCode,notes:form.notes,subtotal,shipping_cost:shipping.cost,total,status:'pending',payment_status:'pending'}).select().single(); if(error){setLoading(false); return alert(error.message)} const orderItems=items.map(item=>({order_id:data.id,product_id:item.productId,variant_id:item.variantId,product_name:item.name,size:item.size,color:item.color,quantity:item.quantity,unit_price:item.price,total:item.price*item.quantity})); const {error:itemError}=await supabase.from('order_items').insert(orderItems); setLoading(false); if(itemError) return alert(itemError.message); clearCart(); window.location.href=`/pedido-confirmado?orden=${data.id}`; }
  return <main className="section">
    <div className="card p-8 md:p-10"><span className="badge"><CreditCard size={14}/> Checkout manual</span><h1 className="heading-lg mt-4">Finalizar compra</h1><p className="mt-3 max-w-2xl leading-7 text-[#80666b]">Por ahora no usamos Mercado Pago: se genera la orden y queda pendiente para coordinar pago/envío con la tienda.</p></div>
    {!items.length?<div className="card mt-6 p-8"><p>No hay productos para comprar.</p><Link href="/productos" className="btn-primary mt-4">Volver al catálogo</Link></div>:<section className="mt-6 grid gap-6 lg:grid-cols-[1fr_390px]">
      <div className="card p-6 md:p-8"><h2 className="flex items-center gap-2 text-2xl font-black"><ClipboardCheck className="text-[#c6a24a]"/> Datos del cliente</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><input className="input" placeholder="Nombre y apellido" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className="input" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input className="input" placeholder="Teléfono / WhatsApp" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input className="input" placeholder="Código postal" value={form.postalCode} onChange={e=>setForm({...form,postalCode:e.target.value})}/><input className="input md:col-span-2" placeholder="Dirección" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/><input className="input" placeholder="Ciudad" value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/><textarea className="input md:col-span-2" placeholder="Notas opcionales" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div><h2 className="mt-8 flex items-center gap-2 text-2xl font-black"><Truck className="text-[#c6a24a]"/> Envío</h2><div className="mt-4 grid gap-3">{shippingOptions.map(o=><label key={o.id} className={`flex cursor-pointer justify-between rounded-3xl border p-4 transition ${ship===o.id?'border-[#5b2738] bg-[#fff8ef]':'border-[#ead8d0] bg-white'}`}><span className="font-bold"><input type="radio" checked={ship===o.id} onChange={()=>setShip(o.id)} /> {o.name}</span><b>${o.cost.toLocaleString('es-AR')}</b></label>)}</div></div>
      <aside className="card h-fit p-6 lg:sticky lg:top-32"><h2 className="text-2xl font-black">Resumen</h2>{items.map(item=><div className="mt-4 flex justify-between gap-4 text-sm" key={item.variantId}><span>{item.quantity}× {item.name}<br/><small className="text-[#80666b]">{item.size} · {item.color}</small></span><b>${(item.quantity*item.price).toLocaleString('es-AR')}</b></div>)}<div className="gold-line my-5"/><div className="flex justify-between"><span>Subtotal</span><b>${subtotal.toLocaleString('es-AR')}</b></div><div className="mt-2 flex justify-between"><span>Envío</span><b>${shipping.cost.toLocaleString('es-AR')}</b></div><div className="mt-5 flex justify-between text-2xl"><span>Total</span><b className="text-[#5b2738]">${total.toLocaleString('es-AR')}</b></div><button onClick={createOrder} disabled={loading} className="btn-primary mt-6 w-full">{loading?'Creando orden...':'Confirmar pedido'}</button></aside>
    </section>}
  </main>;
}
